# Generated by Django 3.1.1 on 2020-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201110_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images.jpg', null=True, upload_to='profile picture'),
        ),
    ]
