# Generated by Django 3.1.1 on 2020-11-10 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BDT', 'BDT'), ('INR', 'INR'), ('USD', 'USD')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Others', 'Others')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('IncomeDate', models.DateField()),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Currency', to='Income.currency')),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Source', to='Income.currency')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
