# Generated by Django 3.1.1 on 2020-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Income', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.RemoveField(
            model_name='income',
            name='Currency',
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('BDT', 'BDT'), ('INR', 'INR'), ('USD', 'USD')], default=2020, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='Source',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
