# Generated by Django 3.1.1 on 2020-11-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Income', '0002_auto_20201110_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='IncomeDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
